### ISSUE TITLE
replicationcontroller instead deployment

### ISSUE THREAD

**Issue by eredi93** [GoogleCloudPlatform/kubernetes-workshops#27]
Following this guide: https://github.com/GoogleCloudPlatform/kubernetes-workshops/tree/master/quickstart

If i run: 
`kubectl run lobsters --image=gcr.io/google-samples/lobsters:1.0`

it returns:
`replicationcontroller "lobsters" created`

and **not**:
`deployment "lobsters" created`

**Comment by jeffmendoza** [comment]
Hi, are you on kubernetes v1.1? This should be a deployment in 1.2 or later

**Comment by eredi93** [comment]
I upgraded and is fixed. Thx
